name: Go (Native Matrix)
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: macos-latest
            name: macOS
          - os: windows-latest
            name: Windows
# TODO: Add Fedora back when we figure out the llvm19 issue
#     - os: ubuntu-latest
#       container: fedora:latest
#       name: Fedora (RPM)
# TODO: Add Arch Linux back when we figure out the llvm19 issue
# /github/home/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20250119132755-9dca92dfb4f9/ir.go:931:52: could not determine what C.LLVMConstMul refers to
#   /github/home/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20250119132755-9dca92dfb4f9/ir.go:932:52: could not determine what C.LLVMConstNSWMul refers to
# /github/home/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20250119132755-9dca92dfb4f9/ir.go:933:52: could not determine what C.LLVMConstNUWMul refers to
# /github/home/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20250119132755-9dca92dfb4f9/ir.go:352:38: could not determine what C.LLVMLandingPadCatch refers to
# /github/home/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20250119132755-9dca92dfb4f9/ir.go:79:22: could not determine what C.LLVMLandingPadClauseTy refers to
# /github/home/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20250119132755-9dca92dfb4f9/ir.go:353:38: could not determine what C.LLVMLandingPadFilter refers to
#  - os: ubuntu-latest
#    container: archlinux:latest
#    name: Arch Linux
          - os: ubuntu-latest
            container: alpine:latest
            name: Alpine Linux
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    name: Build & Test (${{ matrix.name }})
    env:
      CGO_ENABLED: 1
      GOFLAGS: -tags=llvm19
    steps:
      - name: Install dependencies (Linux Containers)
        if: matrix.container != ''
        run: |
          if [ -f /etc/fedora-release ]; then
            dnf install -y clang clang-devel llvm-devel llvm-static go git gcc-c++ make libffi-devel ncurses-devel zlib-devel pkgconf-pkg-config
          elif [ -f /etc/arch-release ]; then
            pacman -Sy --noconfirm clang llvm go git base-devel pkgconf
          elif [ -f /etc/alpine-release ]; then
            apk add bash clang19 clang19-dev llvm19 llvm19-dev go git build-base pkgconfig zlib-dev ncurses-dev libffi-dev
            ln -s /usr/bin/llvm-config19 /usr/bin/llvm-config
            ln -s /usr/bin/clang-19 /usr/bin/clang
            ln -s /usr/bin/clang++-19 /usr/bin/clang++
            ln -s /usr/bin/llc19 /usr/bin/llc-19
            ln -s /usr/bin/opt19 /usr/bin/opt-19
            ln -s /usr/bin/ld.lld19 /usr/bin/ld.lld-19
            # Symlink headers to standard locations for CGO
            mkdir -p /usr/local/include
            ln -s /usr/lib/llvm19/include/llvm /usr/local/include/llvm
            ln -s /usr/lib/llvm19/include/llvm-c /usr/local/include/llvm-c
          fi
          echo "CC=clang" >> "$GITHUB_ENV"
          echo "CXX=clang++" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4

      - name: Set up Go (Native Runners)
        if: matrix.container == ''
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install LLVM (Native Ubuntu)
        if: matrix.os == 'ubuntu-latest' && matrix.container == ''
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-19 llvm-19-dev lld-19
          sudo ln -s /usr/bin/llvm-config-19 /usr/bin/llvm-config

      - name: Install LLVM (Native macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install llvm@19 lld@19
          echo "$(brew --prefix llvm@19)/bin" >> $GITHUB_PATH
          echo "CC=$(brew --prefix llvm@19)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@19)/bin/clang++" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix llvm@19)/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix llvm@19)/include" >> $GITHUB_ENV

      - name: Install LLVM (Native Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install llvm --version=19.1.0 -y --allow-downgrade --force
          "C:/Program Files/LLVM/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "CC=clang" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "CXX=clang++" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Fix dubious ownership
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build
        working-directory: lang
        shell: bash
        run: |
          if command -v llvm-config >/dev/null 2>&1; then
            INCDIR=$(llvm-config --includedir)
            export CGO_CFLAGS="-I$INCDIR $(llvm-config --cflags | sed 's/\\/\//g')"
            export CGO_CPPFLAGS="-I$INCDIR $(llvm-config --cppflags | sed 's/\\/\//g')"
            export CGO_CXXFLAGS="-I$INCDIR $(llvm-config --cxxflags | sed 's/\\/\//g')"
            export CGO_LDFLAGS="-L$(llvm-config --libdir) $(llvm-config --ldflags --libs all --system-libs | sed 's/\\/\//g')"
          fi
          go build -v -o ../tests/swa main.go

      - name: Test
        working-directory: lang
        shell: bash
        run: |
          if command -v llvm-config >/dev/null 2>&1; then
            INCDIR=$(llvm-config --includedir)
            export CGO_CFLAGS="-I$INCDIR $(llvm-config --cflags | sed 's/\\/\//g')"
            export CGO_CPPFLAGS="-I$INCDIR $(llvm-config --cppflags | sed 's/\\/\//g')"
            export CGO_CXXFLAGS="-I$INCDIR $(llvm-config --cxxflags | sed 's/\\/\//g')"
            export CGO_LDFLAGS="-L$(llvm-config --libdir) $(llvm-config --ldflags --libs all --system-libs | sed 's/\\/\//g')"
          fi
          go test -v -coverprofile=coverage.txt ./...

      - name: Integration Tests
        working-directory: tests
        shell: bash
        run: go test ./...
